import fsExtra from 'fs-extra';
import moment from 'moment';
import path from 'path';
import Client from '../src/frontend/client';
import Server from '../src/backend/server';
import PostData from '../src/types/PostData';
import Post from '../src/backend/models/Post';
import User from '../src/backend/models/User';
import UserData from '../src/types/UserData';

const dbPath = path.join(__dirname, 'test.sqlite');
const server = new Server(dbPath, 3000);
const client = new Client('http://localhost:3000');

// Clear database generated by last test
if (fsExtra.pathExistsSync(dbPath)) {
  fsExtra.unlinkSync(dbPath);
}

test('start server', async () => {
  expect(await server.start()).toEqual(3000);
  expect(server.httpServer).not.toBeUndefined();
});

describe('posts', () => {
  const emptyPost: PostData = {
    author: 0,
    media: 'media.jpg',
    text: 'Hello, World!',
    expires: moment()
      .add(1, 'day')
      .toISOString(),
    date: new Date().toISOString(),
  };
  let postId = '';
  test('create a post', async () => {
    const response = await client.createPost(emptyPost);
    if (response.success === false) {
      console.log(response.error);
    } else if (response.data !== undefined) {
      postId = response.data.id;
      expect(
        await Post.findOne({
          where: {
            id: postId,
          },
        }),
      ).not.toBeNull();
    }
    expect(response.success).toBeTruthy();
  });
  test('get a post', async () => {
    const response = await client.getPost(postId);
    if (response.success === false) {
      console.log(response.error);
    } else if (response.data !== undefined) {
      expect(response.data.id).toEqual(postId);
    }
    expect(response.success).toBeTruthy();
  });
});

describe('users', () => {
  const emptyUser: UserData = {
    username: 'user1',
    password: '1234567',
    displayName: 'John Smith',
  };
  test('create a user', async () => {
    const response = await client.createUser(emptyUser);
    if (response.success === false) {
      console.log(response.error);
    } else if (response.data !== undefined) {
      expect(
        await User.findOne({
          where: {
            username: emptyUser.username,
          },
        }),
      ).not.toBeNull();
    }
  });
});

test('stop server', async () => {
  await server.stop();
  expect(server.httpServer).toBeUndefined();
});
