import fsExtra from 'fs-extra';
import path from 'path';
import Client from '../src/frontend/client';
import Server from '../src/backend/server';
import PostData from '../src/types/PostData';
import Post from '../src/backend/models/Post';

const dbPath = path.join(__dirname, 'test.sqlite');
const server = new Server(dbPath, 3000);
const client = new Client('http://localhost:3000');

// Clear database generated by last test
if (fsExtra.pathExistsSync(dbPath)) {
  fsExtra.unlinkSync(dbPath);
}

function stripPost(data: Post): PostData {
  return {
    author: data.author,
    expires: data.expires,
    media: data.media,
    text: data.text,
  };
}

test('start server', async () => {
  expect(await server.start()).toEqual(3000);
  expect(server.httpServer).not.toBeUndefined();
});

describe('posts', () => {
  const emptyPost: PostData = {
    author: 0,
    media: 'media.jpg',
    text: 'Hello, World!',
    expires: new Date().toISOString(),
  };
  let postId = '';
  test('create a post', async () => {
    const response = await client.createPost(emptyPost);
    if (response.success === false) {
      console.log(response.error);
    } else if (response.data !== undefined) {
      postId = response.data.id;
      expect(stripPost(response.data)).toMatchObject(emptyPost);
    }
    expect(response.success).toBeTruthy();
  });
  test('get a post', async () => {
    const response = await client.getPost(postId);
    if (response.success === false) {
      console.log(response.error);
    } else if (response.data !== undefined) {
      expect(stripPost(response.data)).toMatchObject(emptyPost);
    }
    expect(response.success).toBeTruthy();
  });
});

test('stop server', async () => {
  await server.stop();
  expect(server.httpServer).toBeUndefined();
});
